-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 16:04:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Miorecarga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Miorecarga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Miorecarga` DEFAULT CHARACTER SET utf8 ;
USE `Miorecarga` ;

-- -----------------------------------------------------
-- Table `Miorecarga`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Miorecarga`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Miorecarga`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Miorecarga`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `numeroTarjeta` VARCHAR(45) NULL,
  `idPerfil` INT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `idPerfil_idx` (`idPerfil` ASC) VISIBLE,
  CONSTRAINT `idPerfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `Miorecarga`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Miorecarga`.`TipoSaldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Miorecarga`.`TipoSaldo` (
  `idTipoSaldo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoSaldo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Miorecarga`.`Saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Miorecarga`.`Saldo` (
  `idSaldo` INT NOT NULL,
  `idTipoSaldo` VARCHAR(45) NULL,
  `valor` INT NULL,
  `idUsuario` INT NULL,
  `idTipoSaldo` INT NULL,
  PRIMARY KEY (`idSaldo`),
  INDEX `idusuario_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `idtiposaldo_idx` (`idTipoSaldo` ASC) VISIBLE,
  CONSTRAINT `idusuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Miorecarga`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtiposaldo`
    FOREIGN KEY (`idTipoSaldo`)
    REFERENCES `Miorecarga`.`TipoSaldo` (`idTipoSaldo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Miorecarga`.`SaldoHistorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Miorecarga`.`SaldoHistorial` (
  `idSaldoHistorial` INT NOT NULL,
  `valor` INT NULL,
  `fechamovimiento` DATETIME NULL,
  `idSaldo` INT NULL,
  PRIMARY KEY (`idSaldoHistorial`),
  INDEX `idsaldo_idx` (`idSaldo` ASC) VISIBLE,
  CONSTRAINT `idsaldo`
    FOREIGN KEY (`idSaldo`)
    REFERENCES `Miorecarga`.`Saldo` (`idSaldo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
